language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --no-interaction
  - sleep 5

script:
  - bin/phpspec run
  - bin/behat --format progress --stop-on-failure

notifications:
  email: false
