Feature: Developer runs commands to generate config files
  As a Developer
  I want to be able to generate sample configuration files

  Scenario: Running generate:puppet should not overwrite existing config
    Given the file "stamp.yml" contains:
      """
      lorem ipsum...
      """
    When I run command "generate:puppet"
    Then I should see 'The configuration file "stamp.yml" already exists!'

  Scenario: Running generate:puppet
    When I run command "generate:puppet"
    Then I should see 'The configuration file "stamp.yml" was successfully generated.'
     And the file "stamp.json" should contain:
     """
     # This file was auto-generated by stamp
     # For more info visit http://github.com/gajdaw/stamp

     filename:    'metadata.json'
     regex:       '/"version": "(?P<version>[\d\.]+)",/'
     replacement: '"version": "{{ version }}",'
     """
