services:
    stamp.actions.version_parser:
        class: Stamp\Tools\VersionParser

    stamp.actions.variable_container:
        class: Stamp\Tools\VariableContainer

    stamp.actions.major_up:
        class: Stamp\Action\MajorUpAction
        arguments:
            - "@stamp.actions.variable_container"
            - "@stamp.actions.version_parser"

    stamp.actions.minor_up:
        class: Stamp\Action\MinorUpAction
        arguments:
            - "@stamp.actions.variable_container"
            - "@stamp.actions.version_parser"

    stamp.actions.patch_up:
        class: Stamp\Action\PatchUpAction
        arguments:
            - "@stamp.actions.variable_container"
            - "@stamp.actions.version_parser"

    stamp.actions.command:
        class: Stamp\Action\CommandAction
        arguments:
            - "@stamp.actions.variable_container"
            - "@stamp.process"

    stamp.process:
        class: Symfony\Component\Process\Process
        arguments:
            - ""

    stamp.actions.file_reader:
        class: Stamp\Tools\FileReader

    stamp.actions.parse_variable:
        class: Stamp\Action\ParseVariableAction

    stamp.actions.parse_variable_from_file:
        class: Stamp\Action\ParseVariableFromFileAction
        arguments:
            - "@stamp.actions.variable_container"
            - "@stamp.actions.file_reader"
            - "@stamp.actions.parse_variable"

    stamp.actions.save_variable_to_file:
        class: Stamp\Action\SaveVariableToFileAction
        arguments:
            - "@stamp.actions.variable_container"
            - "@stamp.actions.file_reader"


