services:
    stamp.actions.version_parser:
        class: Stamp\Action\VersionParser

    stamp.actions.variable_container:
        class: Stamp\Action\VariableContainer

    stamp.actions.major_up:
        class: Stamp\Action\MajorUp
        arguments:
            - "@stamp.actions.version_parser"
            - "@stamp.actions.variable_container"

    stamp.actions.file_reader:
        class: Stamp\Action\FileReader

    stamp.actions.parse_variable:
        class: Stamp\Action\ParseVariable

    stamp.actions.parse_variable_from_file:
        class: Stamp\Action\ParseVariableFromFile
        arguments:
            - "@stamp.actions.file_reader"
            - "@stamp.actions.parse_variable"
            - "@stamp.actions.variable_container"


